### ISSUE TITLE
35. Admin Invoice Show Page: Total Revenue

### ISSUE THREAD

**Issue by MoxieMax** [Pocketzs/little-esty-shop#37]
As an admin
When I visit an admin invoice show page
Then I see the total revenue that will be generated from this invoice

**Comment by JustJakeSeymour** [comment]
This is going to be a bit more complicated to do in active record (there's a way to use ruby for it, but I'm sure they want us to use some sort of group or aggregate to accomplish this)

Going to stop for the night and resume Thursday Morning
